name: gnn_dev_torch
channels:
  - rapidsai
  - rapidsai-nightly
  - conda-forge
dependencies:
  - clang==11.1.0
  - clang-tools=11.1.0
  - compilers
  - doxygen=1.8.20
  - sysroot_linux-64=2.17

  # already in base container
  #- cython>=0.29,<0.30
  #- cuda-python>=11.5,<11.7.1
  #- libraft-headers=22.12.*
  #- jupyter
  #- matplotlib
  #- ninja
  #- numpy>=1.17
  #- ogb
  #- pandas
  #- pytest>=4.6
  #- pyyaml
  #- scikit-learn>=0.21
  #- scipy
  #- wget

  # pip
  #- cmake>=3.23.1,!=3.25.0
  #- clang=11.1.0
  #- clang-tools=11.1.0
  #- doxygen=1.8.20
  #- flake8
  #- mpi4py
  #- nanobind>0.0.7
  #- scikit-build>=0.13.1